# Generated by Django 5.2.7 on 2025-11-01 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_a2amessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2amessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.user'),
        ),
    ]
